from langchain_ollama.llms import OllamaLLM
from langchain_core.prompts import ChatPromptTemplate
from vector import retriever

model = OllamaLLM(model="llama3.2")

template = """
You are an expert in analyzing hourly energy generation data.
Use the retrieved records to calculate totals, averages, and comparisons.

Important:
- "mw" represents megawatts generated.
- If multiple records exist for the same fuel type and date, sum them.
- If asked about trends, consider sequential dates.

Relevant data:
{raw_data}

Question:
{question}

Provide a clear, concise, and factual answer.
If unsure, say 'I don't have enough information.'
"""
prompt = ChatPromptTemplate.from_template(template)
chain = prompt | model

while True:
    print("\n\n-------------------------------")
    question = input("Ask your question (q to quit): ")
    print("\n\n")
    if question == "q":
        break
    
    raw_data = retriever.invoke(question)
    result = chain.invoke({"raw_data": raw_data, "question": question})
    print(result)


# Example questions to ask:
# What was the fuel type that generated the most energy on October 23?
# Which fuel type generated the least amount of energy on October 20?
# What was the total energy generated by solar power on October 19?
